//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ValidateAdminQR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://qrvalidateadmin.wsbeans.iseries/", ConfigurationName="MR_ValidateAdminQR.QRValidateAdminServices")]
    public interface QRValidateAdminServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://qrvalidateadmin.wsbeans.iseries/QRValidateAdminServices/mtrvaladmcRequest", ReplyAction="http://qrvalidateadmin.wsbeans.iseries/QRValidateAdminServices/mtrvaladmcResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse mtrvaladmc(WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://qrvalidateadmin.wsbeans.iseries/QRValidateAdminServices/mtrvaladmcRequest", ReplyAction="http://qrvalidateadmin.wsbeans.iseries/QRValidateAdminServices/mtrvaladmcResponse" +
            "")]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse> mtrvaladmcAsync(WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qrvalidateadmin.wsbeans.iseries/")]
    public partial class mtrvaladmcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_QRTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_QRTEXT {
            get {
                return this.i_QRTEXTField;
            }
            set {
                this.i_QRTEXTField = value;
                this.RaisePropertyChanged("I_QRTEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qrvalidateadmin.wsbeans.iseries/")]
    public partial class mtrvaladmcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_OBJECTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_OBJECT {
            get {
                return this.o_OBJECTField;
            }
            set {
                this.o_OBJECTField = value;
                this.RaisePropertyChanged("O_OBJECT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvaladmc", WrapperNamespace="http://qrvalidateadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvaladmcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qrvalidateadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateAdminQR.mtrvaladmcInput arg0;
        
        public mtrvaladmcRequest() {
        }
        
        public mtrvaladmcRequest(WPFMultired.MR_ValidateAdminQR.mtrvaladmcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvaladmcResponse", WrapperNamespace="http://qrvalidateadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvaladmcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://qrvalidateadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateAdminQR.mtrvaladmcResult @return;
        
        public mtrvaladmcResponse() {
        }
        
        public mtrvaladmcResponse(WPFMultired.MR_ValidateAdminQR.mtrvaladmcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QRValidateAdminServicesChannel : WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QRValidateAdminServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices>, WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices {
        
        public QRValidateAdminServicesClient() {
        }
        
        public QRValidateAdminServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QRValidateAdminServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRValidateAdminServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRValidateAdminServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices.mtrvaladmc(WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest request) {
            return base.Channel.mtrvaladmc(request);
        }
        
        public WPFMultired.MR_ValidateAdminQR.mtrvaladmcResult mtrvaladmc(WPFMultired.MR_ValidateAdminQR.mtrvaladmcInput arg0) {
            WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest inValue = new WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse retVal = ((WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices)(this)).mtrvaladmc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse> WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices.mtrvaladmcAsync(WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest request) {
            return base.Channel.mtrvaladmcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ValidateAdminQR.mtrvaladmcResponse> mtrvaladmcAsync(WPFMultired.MR_ValidateAdminQR.mtrvaladmcInput arg0) {
            WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest inValue = new WPFMultired.MR_ValidateAdminQR.mtrvaladmcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ValidateAdminQR.QRValidateAdminServices)(this)).mtrvaladmcAsync(inValue);
        }
    }
}
