//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ValidateOTP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validarotp.wsbeans.iseries/", ConfigurationName="MR_ValidateOTP.ValidarOTPServices")]
    public interface ValidarOTPServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://validarotp.wsbeans.iseries/ValidarOTPServices/mtrvalotpRequest", ReplyAction="http://validarotp.wsbeans.iseries/ValidarOTPServices/mtrvalotpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ValidateOTP.mtrvalotpResponse mtrvalotp(WPFMultired.MR_ValidateOTP.mtrvalotpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validarotp.wsbeans.iseries/ValidarOTPServices/mtrvalotpRequest", ReplyAction="http://validarotp.wsbeans.iseries/ValidarOTPServices/mtrvalotpResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateOTP.mtrvalotpResponse> mtrvalotpAsync(WPFMultired.MR_ValidateOTP.mtrvalotpRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validarotp.wsbeans.iseries/")]
    public partial class mtrvalotpInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TOKENField;
        
        private string i_REFERENCIAField;
        
        private string i_VALORField;
        
        private string i_CUENTAField;
        
        private string i_SISTEMAField;
        
        private string i_PRODUCTOField;
        
        private string i_TIPOTRNField;
        
        private string i_CODIGOTPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TOKEN {
            get {
                return this.i_TOKENField;
            }
            set {
                this.i_TOKENField = value;
                this.RaisePropertyChanged("I_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_REFERENCIA {
            get {
                return this.i_REFERENCIAField;
            }
            set {
                this.i_REFERENCIAField = value;
                this.RaisePropertyChanged("I_REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_VALOR {
            get {
                return this.i_VALORField;
            }
            set {
                this.i_VALORField = value;
                this.RaisePropertyChanged("I_VALOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_CUENTA {
            get {
                return this.i_CUENTAField;
            }
            set {
                this.i_CUENTAField = value;
                this.RaisePropertyChanged("I_CUENTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string I_SISTEMA {
            get {
                return this.i_SISTEMAField;
            }
            set {
                this.i_SISTEMAField = value;
                this.RaisePropertyChanged("I_SISTEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string I_PRODUCTO {
            get {
                return this.i_PRODUCTOField;
            }
            set {
                this.i_PRODUCTOField = value;
                this.RaisePropertyChanged("I_PRODUCTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string I_TIPOTRN {
            get {
                return this.i_TIPOTRNField;
            }
            set {
                this.i_TIPOTRNField = value;
                this.RaisePropertyChanged("I_TIPOTRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string I_CODIGOTP {
            get {
                return this.i_CODIGOTPField;
            }
            set {
                this.i_CODIGOTPField = value;
                this.RaisePropertyChanged("I_CODIGOTP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validarotp.wsbeans.iseries/")]
    public partial class mtrvalotpResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvalotp", WrapperNamespace="http://validarotp.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvalotpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validarotp.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateOTP.mtrvalotpInput arg0;
        
        public mtrvalotpRequest() {
        }
        
        public mtrvalotpRequest(WPFMultired.MR_ValidateOTP.mtrvalotpInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvalotpResponse", WrapperNamespace="http://validarotp.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvalotpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validarotp.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateOTP.mtrvalotpResult @return;
        
        public mtrvalotpResponse() {
        }
        
        public mtrvalotpResponse(WPFMultired.MR_ValidateOTP.mtrvalotpResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidarOTPServicesChannel : WPFMultired.MR_ValidateOTP.ValidarOTPServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarOTPServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ValidateOTP.ValidarOTPServices>, WPFMultired.MR_ValidateOTP.ValidarOTPServices {
        
        public ValidarOTPServicesClient() {
        }
        
        public ValidarOTPServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidarOTPServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarOTPServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarOTPServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ValidateOTP.mtrvalotpResponse WPFMultired.MR_ValidateOTP.ValidarOTPServices.mtrvalotp(WPFMultired.MR_ValidateOTP.mtrvalotpRequest request) {
            return base.Channel.mtrvalotp(request);
        }
        
        public WPFMultired.MR_ValidateOTP.mtrvalotpResult mtrvalotp(WPFMultired.MR_ValidateOTP.mtrvalotpInput arg0) {
            WPFMultired.MR_ValidateOTP.mtrvalotpRequest inValue = new WPFMultired.MR_ValidateOTP.mtrvalotpRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ValidateOTP.mtrvalotpResponse retVal = ((WPFMultired.MR_ValidateOTP.ValidarOTPServices)(this)).mtrvalotp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateOTP.mtrvalotpResponse> WPFMultired.MR_ValidateOTP.ValidarOTPServices.mtrvalotpAsync(WPFMultired.MR_ValidateOTP.mtrvalotpRequest request) {
            return base.Channel.mtrvalotpAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ValidateOTP.mtrvalotpResponse> mtrvalotpAsync(WPFMultired.MR_ValidateOTP.mtrvalotpInput arg0) {
            WPFMultired.MR_ValidateOTP.mtrvalotpRequest inValue = new WPFMultired.MR_ValidateOTP.mtrvalotpRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ValidateOTP.ValidarOTPServices)(this)).mtrvalotpAsync(inValue);
        }
    }
}
