//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ValidateTOTP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validatetotpmultired.wsbeans.iseries/", ConfigurationName="MR_ValidateTOTP.ValidateTOTPMultiRedServices")]
    public interface ValidateTOTPMultiRedServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://validatetotpmultired.wsbeans.iseries/ValidateTOTPMultiRedServices/mtrvatot" +
            "pcRequest", ReplyAction="http://validatetotpmultired.wsbeans.iseries/ValidateTOTPMultiRedServices/mtrvatot" +
            "pcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse mtrvatotpc(WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validatetotpmultired.wsbeans.iseries/ValidateTOTPMultiRedServices/mtrvatot" +
            "pcRequest", ReplyAction="http://validatetotpmultired.wsbeans.iseries/ValidateTOTPMultiRedServices/mtrvatot" +
            "pcResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse> mtrvatotpcAsync(WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validatetotpmultired.wsbeans.iseries/")]
    public partial class mtrvatotpcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_KEYREDField;
        
        private string i_KEYOTPField;
        
        private string i_CODOTPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_KEYRED {
            get {
                return this.i_KEYREDField;
            }
            set {
                this.i_KEYREDField = value;
                this.RaisePropertyChanged("I_KEYRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_KEYOTP {
            get {
                return this.i_KEYOTPField;
            }
            set {
                this.i_KEYOTPField = value;
                this.RaisePropertyChanged("I_KEYOTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_CODOTP {
            get {
                return this.i_CODOTPField;
            }
            set {
                this.i_CODOTPField = value;
                this.RaisePropertyChanged("I_CODOTP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validatetotpmultired.wsbeans.iseries/")]
    public partial class mtrvatotpcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_RESULT {
            get {
                return this.o_RESULTField;
            }
            set {
                this.o_RESULTField = value;
                this.RaisePropertyChanged("O_RESULT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvatotpc", WrapperNamespace="http://validatetotpmultired.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvatotpcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validatetotpmultired.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateTOTP.mtrvatotpcInput arg0;
        
        public mtrvatotpcRequest() {
        }
        
        public mtrvatotpcRequest(WPFMultired.MR_ValidateTOTP.mtrvatotpcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvatotpcResponse", WrapperNamespace="http://validatetotpmultired.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvatotpcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validatetotpmultired.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateTOTP.mtrvatotpcResult @return;
        
        public mtrvatotpcResponse() {
        }
        
        public mtrvatotpcResponse(WPFMultired.MR_ValidateTOTP.mtrvatotpcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateTOTPMultiRedServicesChannel : WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateTOTPMultiRedServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices>, WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices {
        
        public ValidateTOTPMultiRedServicesClient() {
        }
        
        public ValidateTOTPMultiRedServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateTOTPMultiRedServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTOTPMultiRedServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTOTPMultiRedServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices.mtrvatotpc(WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest request) {
            return base.Channel.mtrvatotpc(request);
        }
        
        public WPFMultired.MR_ValidateTOTP.mtrvatotpcResult mtrvatotpc(WPFMultired.MR_ValidateTOTP.mtrvatotpcInput arg0) {
            WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest inValue = new WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse retVal = ((WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices)(this)).mtrvatotpc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse> WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices.mtrvatotpcAsync(WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest request) {
            return base.Channel.mtrvatotpcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ValidateTOTP.mtrvatotpcResponse> mtrvatotpcAsync(WPFMultired.MR_ValidateTOTP.mtrvatotpcInput arg0) {
            WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest inValue = new WPFMultired.MR_ValidateTOTP.mtrvatotpcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ValidateTOTP.ValidateTOTPMultiRedServices)(this)).mtrvatotpcAsync(inValue);
        }
    }
}
