//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ListProducts {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/", ConfigurationName="MR_ListProducts.ConsultarProductosClienteServices")]
    public interface ConsultarProductosClienteServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://consultarproductoscliente.wsbeans.iseries/ConsultarProductosClienteService" +
            "s/mtrprocliRequest", ReplyAction="http://consultarproductoscliente.wsbeans.iseries/ConsultarProductosClienteService" +
            "s/mtrprocliResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ListProducts.mtrprocliResponse mtrprocli(WPFMultired.MR_ListProducts.mtrprocliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://consultarproductoscliente.wsbeans.iseries/ConsultarProductosClienteService" +
            "s/mtrprocliRequest", ReplyAction="http://consultarproductoscliente.wsbeans.iseries/ConsultarProductosClienteService" +
            "s/mtrprocliResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ListProducts.mtrprocliResponse> mtrprocliAsync(WPFMultired.MR_ListProducts.mtrprocliRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/")]
    public partial class mtrprocliInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TIPODOCUMENTOField;
        
        private string i_NUMERODOCUMENTOField;
        
        private string i_TIPOTRANSACCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TIPODOCUMENTO {
            get {
                return this.i_TIPODOCUMENTOField;
            }
            set {
                this.i_TIPODOCUMENTOField = value;
                this.RaisePropertyChanged("I_TIPODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_NUMERODOCUMENTO {
            get {
                return this.i_NUMERODOCUMENTOField;
            }
            set {
                this.i_NUMERODOCUMENTOField = value;
                this.RaisePropertyChanged("I_NUMERODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_TIPOTRANSACCION {
            get {
                return this.i_TIPOTRANSACCIONField;
            }
            set {
                this.i_TIPOTRANSACCIONField = value;
                this.RaisePropertyChanged("I_TIPOTRANSACCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/")]
    public partial class oLISTAREGISTROSLIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_NOMPROField;
        
        private string o_NROCTAField;
        
        private string o_CODSISField;
        
        private string o_CODPROField;
        
        private string o_CTAMASField;
        
        private string o_MONMINField;
        
        private string o_MONMAXField;
        
        private string o_VLRCOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_NOMPRO {
            get {
                return this.o_NOMPROField;
            }
            set {
                this.o_NOMPROField = value;
                this.RaisePropertyChanged("O_NOMPRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_NROCTA {
            get {
                return this.o_NROCTAField;
            }
            set {
                this.o_NROCTAField = value;
                this.RaisePropertyChanged("O_NROCTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_CODSIS {
            get {
                return this.o_CODSISField;
            }
            set {
                this.o_CODSISField = value;
                this.RaisePropertyChanged("O_CODSIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_CODPRO {
            get {
                return this.o_CODPROField;
            }
            set {
                this.o_CODPROField = value;
                this.RaisePropertyChanged("O_CODPRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_CTAMAS {
            get {
                return this.o_CTAMASField;
            }
            set {
                this.o_CTAMASField = value;
                this.RaisePropertyChanged("O_CTAMAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_MONMIN {
            get {
                return this.o_MONMINField;
            }
            set {
                this.o_MONMINField = value;
                this.RaisePropertyChanged("O_MONMIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string O_MONMAX {
            get {
                return this.o_MONMAXField;
            }
            set {
                this.o_MONMAXField = value;
                this.RaisePropertyChanged("O_MONMAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string O_VLRCOM {
            get {
                return this.o_VLRCOMField;
            }
            set {
                this.o_VLRCOMField = value;
                this.RaisePropertyChanged("O_VLRCOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/")]
    public partial class oLISTAREGISTROS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long o_RTNCONField;
        
        private oLISTAREGISTROSLIST[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long O_RTNCON {
            get {
                return this.o_RTNCONField;
            }
            set {
                this.o_RTNCONField = value;
                this.RaisePropertyChanged("O_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public oLISTAREGISTROSLIST[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/")]
    public partial class mtrprocliResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_NOMBRECLIENTEField;
        
        private string o_TOKENTRANSACCIONField;
        
        private string o_REFERENCIATRANSACCIONField;
        
        private oLISTAREGISTROS o_LISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_NOMBRECLIENTE {
            get {
                return this.o_NOMBRECLIENTEField;
            }
            set {
                this.o_NOMBRECLIENTEField = value;
                this.RaisePropertyChanged("O_NOMBRECLIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_TOKENTRANSACCION {
            get {
                return this.o_TOKENTRANSACCIONField;
            }
            set {
                this.o_TOKENTRANSACCIONField = value;
                this.RaisePropertyChanged("O_TOKENTRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_REFERENCIATRANSACCION {
            get {
                return this.o_REFERENCIATRANSACCIONField;
            }
            set {
                this.o_REFERENCIATRANSACCIONField = value;
                this.RaisePropertyChanged("O_REFERENCIATRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public oLISTAREGISTROS O_LISTAREGISTROS {
            get {
                return this.o_LISTAREGISTROSField;
            }
            set {
                this.o_LISTAREGISTROSField = value;
                this.RaisePropertyChanged("O_LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrprocli", WrapperNamespace="http://consultarproductoscliente.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrprocliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ListProducts.mtrprocliInput arg0;
        
        public mtrprocliRequest() {
        }
        
        public mtrprocliRequest(WPFMultired.MR_ListProducts.mtrprocliInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrprocliResponse", WrapperNamespace="http://consultarproductoscliente.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrprocliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultarproductoscliente.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ListProducts.mtrprocliResult @return;
        
        public mtrprocliResponse() {
        }
        
        public mtrprocliResponse(WPFMultired.MR_ListProducts.mtrprocliResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarProductosClienteServicesChannel : WPFMultired.MR_ListProducts.ConsultarProductosClienteServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarProductosClienteServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ListProducts.ConsultarProductosClienteServices>, WPFMultired.MR_ListProducts.ConsultarProductosClienteServices {
        
        public ConsultarProductosClienteServicesClient() {
        }
        
        public ConsultarProductosClienteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarProductosClienteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarProductosClienteServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarProductosClienteServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ListProducts.mtrprocliResponse WPFMultired.MR_ListProducts.ConsultarProductosClienteServices.mtrprocli(WPFMultired.MR_ListProducts.mtrprocliRequest request) {
            return base.Channel.mtrprocli(request);
        }
        
        public WPFMultired.MR_ListProducts.mtrprocliResult mtrprocli(WPFMultired.MR_ListProducts.mtrprocliInput arg0) {
            WPFMultired.MR_ListProducts.mtrprocliRequest inValue = new WPFMultired.MR_ListProducts.mtrprocliRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ListProducts.mtrprocliResponse retVal = ((WPFMultired.MR_ListProducts.ConsultarProductosClienteServices)(this)).mtrprocli(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ListProducts.mtrprocliResponse> WPFMultired.MR_ListProducts.ConsultarProductosClienteServices.mtrprocliAsync(WPFMultired.MR_ListProducts.mtrprocliRequest request) {
            return base.Channel.mtrprocliAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ListProducts.mtrprocliResponse> mtrprocliAsync(WPFMultired.MR_ListProducts.mtrprocliInput arg0) {
            WPFMultired.MR_ListProducts.mtrprocliRequest inValue = new WPFMultired.MR_ListProducts.mtrprocliRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ListProducts.ConsultarProductosClienteServices)(this)).mtrprocliAsync(inValue);
        }
    }
}
