//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ProcessAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://processadmin.wsbeans.iseries/", ConfigurationName="MR_ProcessAdmin.ProcessAdminServices")]
    public interface ProcessAdminServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://processadmin.wsbeans.iseries/ProcessAdminServices/mtrproarqcRequest", ReplyAction="http://processadmin.wsbeans.iseries/ProcessAdminServices/mtrproarqcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ProcessAdmin.mtrproarqcResponse mtrproarqc(WPFMultired.MR_ProcessAdmin.mtrproarqcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://processadmin.wsbeans.iseries/ProcessAdminServices/mtrproarqcRequest", ReplyAction="http://processadmin.wsbeans.iseries/ProcessAdminServices/mtrproarqcResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ProcessAdmin.mtrproarqcResponse> mtrproarqcAsync(WPFMultired.MR_ProcessAdmin.mtrproarqcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processadmin.wsbeans.iseries/")]
    public partial class mtrproarqcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_MOVIMIENTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_MOVIMIENTO {
            get {
                return this.i_MOVIMIENTOField;
            }
            set {
                this.i_MOVIMIENTOField = value;
                this.RaisePropertyChanged("I_MOVIMIENTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processadmin.wsbeans.iseries/")]
    public partial class mtrproarqcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_FECHAPROCESOField;
        
        private string o_FECHASISTEMAField;
        
        private string o_HORATRANSACCIONField;
        
        private string o_CAJEROTRANSACCIONField;
        
        private string o_NUMEROTRANSACCIONField;
        
        private string o_AGENCIATRANSACCIONField;
        
        private string o_VALORTRANSACCIONField;
        
        private string o_NITCAJEROField;
        
        private string o_NOMBRECAJEROField;
        
        private string o_DESCRIPCIONField;
        
        private string o_NOMBREBANCOField;
        
        private string o_NOMBREAGENCIAField;
        
        private string o_CAJEROORIGENField;
        
        private string o_NITCAJEROORIGENField;
        
        private string o_NOMBRECAJEROORIGENField;
        
        private string o_SAFKEYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_FECHAPROCESO {
            get {
                return this.o_FECHAPROCESOField;
            }
            set {
                this.o_FECHAPROCESOField = value;
                this.RaisePropertyChanged("O_FECHAPROCESO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_FECHASISTEMA {
            get {
                return this.o_FECHASISTEMAField;
            }
            set {
                this.o_FECHASISTEMAField = value;
                this.RaisePropertyChanged("O_FECHASISTEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_HORATRANSACCION {
            get {
                return this.o_HORATRANSACCIONField;
            }
            set {
                this.o_HORATRANSACCIONField = value;
                this.RaisePropertyChanged("O_HORATRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_CAJEROTRANSACCION {
            get {
                return this.o_CAJEROTRANSACCIONField;
            }
            set {
                this.o_CAJEROTRANSACCIONField = value;
                this.RaisePropertyChanged("O_CAJEROTRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string O_NUMEROTRANSACCION {
            get {
                return this.o_NUMEROTRANSACCIONField;
            }
            set {
                this.o_NUMEROTRANSACCIONField = value;
                this.RaisePropertyChanged("O_NUMEROTRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string O_AGENCIATRANSACCION {
            get {
                return this.o_AGENCIATRANSACCIONField;
            }
            set {
                this.o_AGENCIATRANSACCIONField = value;
                this.RaisePropertyChanged("O_AGENCIATRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string O_VALORTRANSACCION {
            get {
                return this.o_VALORTRANSACCIONField;
            }
            set {
                this.o_VALORTRANSACCIONField = value;
                this.RaisePropertyChanged("O_VALORTRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string O_NITCAJERO {
            get {
                return this.o_NITCAJEROField;
            }
            set {
                this.o_NITCAJEROField = value;
                this.RaisePropertyChanged("O_NITCAJERO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string O_NOMBRECAJERO {
            get {
                return this.o_NOMBRECAJEROField;
            }
            set {
                this.o_NOMBRECAJEROField = value;
                this.RaisePropertyChanged("O_NOMBRECAJERO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string O_DESCRIPCION {
            get {
                return this.o_DESCRIPCIONField;
            }
            set {
                this.o_DESCRIPCIONField = value;
                this.RaisePropertyChanged("O_DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string O_NOMBREBANCO {
            get {
                return this.o_NOMBREBANCOField;
            }
            set {
                this.o_NOMBREBANCOField = value;
                this.RaisePropertyChanged("O_NOMBREBANCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string O_NOMBREAGENCIA {
            get {
                return this.o_NOMBREAGENCIAField;
            }
            set {
                this.o_NOMBREAGENCIAField = value;
                this.RaisePropertyChanged("O_NOMBREAGENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string O_CAJEROORIGEN {
            get {
                return this.o_CAJEROORIGENField;
            }
            set {
                this.o_CAJEROORIGENField = value;
                this.RaisePropertyChanged("O_CAJEROORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string O_NITCAJEROORIGEN {
            get {
                return this.o_NITCAJEROORIGENField;
            }
            set {
                this.o_NITCAJEROORIGENField = value;
                this.RaisePropertyChanged("O_NITCAJEROORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string O_NOMBRECAJEROORIGEN {
            get {
                return this.o_NOMBRECAJEROORIGENField;
            }
            set {
                this.o_NOMBRECAJEROORIGENField = value;
                this.RaisePropertyChanged("O_NOMBRECAJEROORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string O_SAFKEY {
            get {
                return this.o_SAFKEYField;
            }
            set {
                this.o_SAFKEYField = value;
                this.RaisePropertyChanged("O_SAFKEY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrproarqc", WrapperNamespace="http://processadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrproarqcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ProcessAdmin.mtrproarqcInput arg0;
        
        public mtrproarqcRequest() {
        }
        
        public mtrproarqcRequest(WPFMultired.MR_ProcessAdmin.mtrproarqcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrproarqcResponse", WrapperNamespace="http://processadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrproarqcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ProcessAdmin.mtrproarqcResult @return;
        
        public mtrproarqcResponse() {
        }
        
        public mtrproarqcResponse(WPFMultired.MR_ProcessAdmin.mtrproarqcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessAdminServicesChannel : WPFMultired.MR_ProcessAdmin.ProcessAdminServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessAdminServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ProcessAdmin.ProcessAdminServices>, WPFMultired.MR_ProcessAdmin.ProcessAdminServices {
        
        public ProcessAdminServicesClient() {
        }
        
        public ProcessAdminServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessAdminServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessAdminServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessAdminServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ProcessAdmin.mtrproarqcResponse WPFMultired.MR_ProcessAdmin.ProcessAdminServices.mtrproarqc(WPFMultired.MR_ProcessAdmin.mtrproarqcRequest request) {
            return base.Channel.mtrproarqc(request);
        }
        
        public WPFMultired.MR_ProcessAdmin.mtrproarqcResult mtrproarqc(WPFMultired.MR_ProcessAdmin.mtrproarqcInput arg0) {
            WPFMultired.MR_ProcessAdmin.mtrproarqcRequest inValue = new WPFMultired.MR_ProcessAdmin.mtrproarqcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ProcessAdmin.mtrproarqcResponse retVal = ((WPFMultired.MR_ProcessAdmin.ProcessAdminServices)(this)).mtrproarqc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ProcessAdmin.mtrproarqcResponse> WPFMultired.MR_ProcessAdmin.ProcessAdminServices.mtrproarqcAsync(WPFMultired.MR_ProcessAdmin.mtrproarqcRequest request) {
            return base.Channel.mtrproarqcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ProcessAdmin.mtrproarqcResponse> mtrproarqcAsync(WPFMultired.MR_ProcessAdmin.mtrproarqcInput arg0) {
            WPFMultired.MR_ProcessAdmin.mtrproarqcRequest inValue = new WPFMultired.MR_ProcessAdmin.mtrproarqcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ProcessAdmin.ProcessAdminServices)(this)).mtrproarqcAsync(inValue);
        }
    }
}
