//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ConsultInvoice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/", ConfigurationName="MR_ConsultInvoice.ConsultarFacturasServices")]
    public interface ConsultarFacturasServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://consultarfacturas.wsbeans.iseries/ConsultarFacturasServices/mtrconfaccRequ" +
            "est", ReplyAction="http://consultarfacturas.wsbeans.iseries/ConsultarFacturasServices/mtrconfaccResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ConsultInvoice.mtrconfaccResponse mtrconfacc(WPFMultired.MR_ConsultInvoice.mtrconfaccRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://consultarfacturas.wsbeans.iseries/ConsultarFacturasServices/mtrconfaccRequ" +
            "est", ReplyAction="http://consultarfacturas.wsbeans.iseries/ConsultarFacturasServices/mtrconfaccResp" +
            "onse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ConsultInvoice.mtrconfaccResponse> mtrconfaccAsync(WPFMultired.MR_ConsultInvoice.mtrconfaccRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/")]
    public partial class mtrconfaccInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_LECTURAField;
        
        private string i_TIPODOCUMENTOField;
        
        private string i_REFERENCIAField;
        
        private string i_TIPOTRANSACCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_LECTURA {
            get {
                return this.i_LECTURAField;
            }
            set {
                this.i_LECTURAField = value;
                this.RaisePropertyChanged("I_LECTURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_TIPODOCUMENTO {
            get {
                return this.i_TIPODOCUMENTOField;
            }
            set {
                this.i_TIPODOCUMENTOField = value;
                this.RaisePropertyChanged("I_TIPODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_REFERENCIA {
            get {
                return this.i_REFERENCIAField;
            }
            set {
                this.i_REFERENCIAField = value;
                this.RaisePropertyChanged("I_REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_TIPOTRANSACCION {
            get {
                return this.i_TIPOTRANSACCIONField;
            }
            set {
                this.i_TIPOTRANSACCIONField = value;
                this.RaisePropertyChanged("I_TIPOTRANSACCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/")]
    public partial class listaregistroslist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_REFREDField;
        
        private string o_REFCLIField;
        
        private string o_DESCRIField;
        
        private string o_FLGMODField;
        
        private string o_FLGDETField;
        
        private string o_VLRTOTField;
        
        private string o_VLRRECField;
        
        private string o_VLRCOMField;
        
        private string o_MONMINField;
        
        private string o_MONMAXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_REFRED {
            get {
                return this.o_REFREDField;
            }
            set {
                this.o_REFREDField = value;
                this.RaisePropertyChanged("O_REFRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_REFCLI {
            get {
                return this.o_REFCLIField;
            }
            set {
                this.o_REFCLIField = value;
                this.RaisePropertyChanged("O_REFCLI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_DESCRI {
            get {
                return this.o_DESCRIField;
            }
            set {
                this.o_DESCRIField = value;
                this.RaisePropertyChanged("O_DESCRI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_FLGMOD {
            get {
                return this.o_FLGMODField;
            }
            set {
                this.o_FLGMODField = value;
                this.RaisePropertyChanged("O_FLGMOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_FLGDET {
            get {
                return this.o_FLGDETField;
            }
            set {
                this.o_FLGDETField = value;
                this.RaisePropertyChanged("O_FLGDET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_VLRTOT {
            get {
                return this.o_VLRTOTField;
            }
            set {
                this.o_VLRTOTField = value;
                this.RaisePropertyChanged("O_VLRTOT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string O_VLRREC {
            get {
                return this.o_VLRRECField;
            }
            set {
                this.o_VLRRECField = value;
                this.RaisePropertyChanged("O_VLRREC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string O_VLRCOM {
            get {
                return this.o_VLRCOMField;
            }
            set {
                this.o_VLRCOMField = value;
                this.RaisePropertyChanged("O_VLRCOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string O_MONMIN {
            get {
                return this.o_MONMINField;
            }
            set {
                this.o_MONMINField = value;
                this.RaisePropertyChanged("O_MONMIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string O_MONMAX {
            get {
                return this.o_MONMAXField;
            }
            set {
                this.o_MONMAXField = value;
                this.RaisePropertyChanged("O_MONMAX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/")]
    public partial class listaregistros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long o_RTNCONField;
        
        private listaregistroslist[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long O_RTNCON {
            get {
                return this.o_RTNCONField;
            }
            set {
                this.o_RTNCONField = value;
                this.RaisePropertyChanged("O_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public listaregistroslist[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/")]
    public partial class mtrconfaccResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_TIPOOPERACIONField;
        
        private string o_DESOPERACIONField;
        
        private string o_NUMERODOCUMENTOField;
        
        private string o_NOMBREField;
        
        private string o_VALORGLOBALField;
        
        private listaregistros lISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_TIPOOPERACION {
            get {
                return this.o_TIPOOPERACIONField;
            }
            set {
                this.o_TIPOOPERACIONField = value;
                this.RaisePropertyChanged("O_TIPOOPERACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_DESOPERACION {
            get {
                return this.o_DESOPERACIONField;
            }
            set {
                this.o_DESOPERACIONField = value;
                this.RaisePropertyChanged("O_DESOPERACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_NUMERODOCUMENTO {
            get {
                return this.o_NUMERODOCUMENTOField;
            }
            set {
                this.o_NUMERODOCUMENTOField = value;
                this.RaisePropertyChanged("O_NUMERODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_NOMBRE {
            get {
                return this.o_NOMBREField;
            }
            set {
                this.o_NOMBREField = value;
                this.RaisePropertyChanged("O_NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string O_VALORGLOBAL {
            get {
                return this.o_VALORGLOBALField;
            }
            set {
                this.o_VALORGLOBALField = value;
                this.RaisePropertyChanged("O_VALORGLOBAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public listaregistros LISTAREGISTROS {
            get {
                return this.lISTAREGISTROSField;
            }
            set {
                this.lISTAREGISTROSField = value;
                this.RaisePropertyChanged("LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrconfacc", WrapperNamespace="http://consultarfacturas.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrconfaccRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ConsultInvoice.mtrconfaccInput arg0;
        
        public mtrconfaccRequest() {
        }
        
        public mtrconfaccRequest(WPFMultired.MR_ConsultInvoice.mtrconfaccInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrconfaccResponse", WrapperNamespace="http://consultarfacturas.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrconfaccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultarfacturas.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ConsultInvoice.mtrconfaccResult @return;
        
        public mtrconfaccResponse() {
        }
        
        public mtrconfaccResponse(WPFMultired.MR_ConsultInvoice.mtrconfaccResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarFacturasServicesChannel : WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarFacturasServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices>, WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices {
        
        public ConsultarFacturasServicesClient() {
        }
        
        public ConsultarFacturasServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarFacturasServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarFacturasServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarFacturasServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ConsultInvoice.mtrconfaccResponse WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices.mtrconfacc(WPFMultired.MR_ConsultInvoice.mtrconfaccRequest request) {
            return base.Channel.mtrconfacc(request);
        }
        
        public WPFMultired.MR_ConsultInvoice.mtrconfaccResult mtrconfacc(WPFMultired.MR_ConsultInvoice.mtrconfaccInput arg0) {
            WPFMultired.MR_ConsultInvoice.mtrconfaccRequest inValue = new WPFMultired.MR_ConsultInvoice.mtrconfaccRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ConsultInvoice.mtrconfaccResponse retVal = ((WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices)(this)).mtrconfacc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ConsultInvoice.mtrconfaccResponse> WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices.mtrconfaccAsync(WPFMultired.MR_ConsultInvoice.mtrconfaccRequest request) {
            return base.Channel.mtrconfaccAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ConsultInvoice.mtrconfaccResponse> mtrconfaccAsync(WPFMultired.MR_ConsultInvoice.mtrconfaccInput arg0) {
            WPFMultired.MR_ConsultInvoice.mtrconfaccRequest inValue = new WPFMultired.MR_ConsultInvoice.mtrconfaccRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ConsultInvoice.ConsultarFacturasServices)(this)).mtrconfaccAsync(inValue);
        }
    }
}
