//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ControllCash {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asmcontroller.wsbeans.iseries/", ConfigurationName="MR_ControllCash.ASMControllerServices")]
    public interface ASMControllerServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://asmcontroller.wsbeans.iseries/ASMControllerServices/mtrctlbllcRequest", ReplyAction="http://asmcontroller.wsbeans.iseries/ASMControllerServices/mtrctlbllcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ControllCash.mtrctlbllcResponse mtrctlbllc(WPFMultired.MR_ControllCash.mtrctlbllcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmcontroller.wsbeans.iseries/ASMControllerServices/mtrctlbllcRequest", ReplyAction="http://asmcontroller.wsbeans.iseries/ASMControllerServices/mtrctlbllcResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ControllCash.mtrctlbllcResponse> mtrctlbllcAsync(WPFMultired.MR_ControllCash.mtrctlbllcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmcontroller.wsbeans.iseries/")]
    public partial class mtrctlbllcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TRANSACCIONField;
        
        private string i_ESTADOField;
        
        private string i_TRNTAYLORField;
        
        private iLISTAREGISTROS i_LISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TRANSACCION {
            get {
                return this.i_TRANSACCIONField;
            }
            set {
                this.i_TRANSACCIONField = value;
                this.RaisePropertyChanged("I_TRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_ESTADO {
            get {
                return this.i_ESTADOField;
            }
            set {
                this.i_ESTADOField = value;
                this.RaisePropertyChanged("I_ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_TRNTAYLOR {
            get {
                return this.i_TRNTAYLORField;
            }
            set {
                this.i_TRNTAYLORField = value;
                this.RaisePropertyChanged("I_TRNTAYLOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public iLISTAREGISTROS I_LISTAREGISTROS {
            get {
                return this.i_LISTAREGISTROSField;
            }
            set {
                this.i_LISTAREGISTROSField = value;
                this.RaisePropertyChanged("I_LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmcontroller.wsbeans.iseries/")]
    public partial class iLISTAREGISTROS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long i_RTNCONField;
        
        private iLISTAREGISTROSLIST[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long I_RTNCON {
            get {
                return this.i_RTNCONField;
            }
            set {
                this.i_RTNCONField = value;
                this.RaisePropertyChanged("I_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public iLISTAREGISTROSLIST[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmcontroller.wsbeans.iseries/")]
    public partial class iLISTAREGISTROSLIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_CODMONField;
        
        private string i_TIPOMBField;
        
        private string i_DENOMIField;
        
        private string i_CANTIDField;
        
        private string i_TIPDEVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_CODMON {
            get {
                return this.i_CODMONField;
            }
            set {
                this.i_CODMONField = value;
                this.RaisePropertyChanged("I_CODMON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_TIPOMB {
            get {
                return this.i_TIPOMBField;
            }
            set {
                this.i_TIPOMBField = value;
                this.RaisePropertyChanged("I_TIPOMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_DENOMI {
            get {
                return this.i_DENOMIField;
            }
            set {
                this.i_DENOMIField = value;
                this.RaisePropertyChanged("I_DENOMI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANTID {
            get {
                return this.i_CANTIDField;
            }
            set {
                this.i_CANTIDField = value;
                this.RaisePropertyChanged("I_CANTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_TIPDEV {
            get {
                return this.i_TIPDEVField;
            }
            set {
                this.i_TIPDEVField = value;
                this.RaisePropertyChanged("I_TIPDEV");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmcontroller.wsbeans.iseries/")]
    public partial class mtrctlbllcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_RESULTADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_RESULTADO {
            get {
                return this.o_RESULTADOField;
            }
            set {
                this.o_RESULTADOField = value;
                this.RaisePropertyChanged("O_RESULTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrctlbllc", WrapperNamespace="http://asmcontroller.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrctlbllcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmcontroller.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ControllCash.mtrctlbllcInput arg0;
        
        public mtrctlbllcRequest() {
        }
        
        public mtrctlbllcRequest(WPFMultired.MR_ControllCash.mtrctlbllcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrctlbllcResponse", WrapperNamespace="http://asmcontroller.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrctlbllcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmcontroller.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ControllCash.mtrctlbllcResult @return;
        
        public mtrctlbllcResponse() {
        }
        
        public mtrctlbllcResponse(WPFMultired.MR_ControllCash.mtrctlbllcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ASMControllerServicesChannel : WPFMultired.MR_ControllCash.ASMControllerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASMControllerServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ControllCash.ASMControllerServices>, WPFMultired.MR_ControllCash.ASMControllerServices {
        
        public ASMControllerServicesClient() {
        }
        
        public ASMControllerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASMControllerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASMControllerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASMControllerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ControllCash.mtrctlbllcResponse WPFMultired.MR_ControllCash.ASMControllerServices.mtrctlbllc(WPFMultired.MR_ControllCash.mtrctlbllcRequest request) {
            return base.Channel.mtrctlbllc(request);
        }
        
        public WPFMultired.MR_ControllCash.mtrctlbllcResult mtrctlbllc(WPFMultired.MR_ControllCash.mtrctlbllcInput arg0) {
            WPFMultired.MR_ControllCash.mtrctlbllcRequest inValue = new WPFMultired.MR_ControllCash.mtrctlbllcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ControllCash.mtrctlbllcResponse retVal = ((WPFMultired.MR_ControllCash.ASMControllerServices)(this)).mtrctlbllc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ControllCash.mtrctlbllcResponse> WPFMultired.MR_ControllCash.ASMControllerServices.mtrctlbllcAsync(WPFMultired.MR_ControllCash.mtrctlbllcRequest request) {
            return base.Channel.mtrctlbllcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ControllCash.mtrctlbllcResponse> mtrctlbllcAsync(WPFMultired.MR_ControllCash.mtrctlbllcInput arg0) {
            WPFMultired.MR_ControllCash.mtrctlbllcRequest inValue = new WPFMultired.MR_ControllCash.mtrctlbllcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ControllCash.ASMControllerServices)(this)).mtrctlbllcAsync(inValue);
        }
    }
}
