//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ValidateStatusAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validatestatusadmin.wsbeans.iseries/", ConfigurationName="MR_ValidateStatusAdmin.ValidateStatusAdminServices")]
    public interface ValidateStatusAdminServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://validatestatusadmin.wsbeans.iseries/ValidateStatusAdminServices/mtrvalarqc" +
            "Request", ReplyAction="http://validatestatusadmin.wsbeans.iseries/ValidateStatusAdminServices/mtrvalarqc" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse mtrvalarqc(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validatestatusadmin.wsbeans.iseries/ValidateStatusAdminServices/mtrvalarqc" +
            "Request", ReplyAction="http://validatestatusadmin.wsbeans.iseries/ValidateStatusAdminServices/mtrvalarqc" +
            "Response")]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse> mtrvalarqcAsync(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validatestatusadmin.wsbeans.iseries/")]
    public partial class mtrvalarqcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validatestatusadmin.wsbeans.iseries/")]
    public partial class mtrvalarqcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_MOVIMIENTOField;
        
        private string o_DESCRIPCIONField;
        
        private string o_STATUSACEPTADORField;
        
        private string o_STATUSDISPENSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_MOVIMIENTO {
            get {
                return this.o_MOVIMIENTOField;
            }
            set {
                this.o_MOVIMIENTOField = value;
                this.RaisePropertyChanged("O_MOVIMIENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_DESCRIPCION {
            get {
                return this.o_DESCRIPCIONField;
            }
            set {
                this.o_DESCRIPCIONField = value;
                this.RaisePropertyChanged("O_DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_STATUSACEPTADOR {
            get {
                return this.o_STATUSACEPTADORField;
            }
            set {
                this.o_STATUSACEPTADORField = value;
                this.RaisePropertyChanged("O_STATUSACEPTADOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_STATUSDISPENSER {
            get {
                return this.o_STATUSDISPENSERField;
            }
            set {
                this.o_STATUSDISPENSERField = value;
                this.RaisePropertyChanged("O_STATUSDISPENSER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvalarqc", WrapperNamespace="http://validatestatusadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvalarqcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validatestatusadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcInput arg0;
        
        public mtrvalarqcRequest() {
        }
        
        public mtrvalarqcRequest(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrvalarqcResponse", WrapperNamespace="http://validatestatusadmin.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrvalarqcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validatestatusadmin.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResult @return;
        
        public mtrvalarqcResponse() {
        }
        
        public mtrvalarqcResponse(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateStatusAdminServicesChannel : WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateStatusAdminServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices>, WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices {
        
        public ValidateStatusAdminServicesClient() {
        }
        
        public ValidateStatusAdminServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateStatusAdminServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateStatusAdminServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateStatusAdminServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices.mtrvalarqc(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest request) {
            return base.Channel.mtrvalarqc(request);
        }
        
        public WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResult mtrvalarqc(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcInput arg0) {
            WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest inValue = new WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse retVal = ((WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices)(this)).mtrvalarqc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse> WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices.mtrvalarqcAsync(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest request) {
            return base.Channel.mtrvalarqcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcResponse> mtrvalarqcAsync(WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcInput arg0) {
            WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest inValue = new WPFMultired.MR_ValidateStatusAdmin.mtrvalarqcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ValidateStatusAdmin.ValidateStatusAdminServices)(this)).mtrvalarqcAsync(inValue);
        }
    }
}
