//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_ReportTransaction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/", ConfigurationName="MR_ReportTransaction.ProcesarTransaccionServices")]
    public interface ProcesarTransaccionServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://procesartransaccion.wsbeans.iseries/ProcesarTransaccionServices/mtrprotrnR" +
            "equest", ReplyAction="http://procesartransaccion.wsbeans.iseries/ProcesarTransaccionServices/mtrprotrnR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_ReportTransaction.mtrprotrnResponse mtrprotrn(WPFMultired.MR_ReportTransaction.mtrprotrnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://procesartransaccion.wsbeans.iseries/ProcesarTransaccionServices/mtrprotrnR" +
            "equest", ReplyAction="http://procesartransaccion.wsbeans.iseries/ProcesarTransaccionServices/mtrprotrnR" +
            "esponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_ReportTransaction.mtrprotrnResponse> mtrprotrnAsync(WPFMultired.MR_ReportTransaction.mtrprotrnRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/")]
    public partial class mtrprotrnInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TOKENField;
        
        private string i_REFERENCIAField;
        
        private string i_CODIGOTPField;
        
        private string i_VALORField;
        
        private string i_CUENTAField;
        
        private string i_SISTEMAField;
        
        private string i_PRODUCTOField;
        
        private string i_TIPOTRNField;
        
        private iLISTAREGISTROS i_LISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TOKEN {
            get {
                return this.i_TOKENField;
            }
            set {
                this.i_TOKENField = value;
                this.RaisePropertyChanged("I_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_REFERENCIA {
            get {
                return this.i_REFERENCIAField;
            }
            set {
                this.i_REFERENCIAField = value;
                this.RaisePropertyChanged("I_REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_CODIGOTP {
            get {
                return this.i_CODIGOTPField;
            }
            set {
                this.i_CODIGOTPField = value;
                this.RaisePropertyChanged("I_CODIGOTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_VALOR {
            get {
                return this.i_VALORField;
            }
            set {
                this.i_VALORField = value;
                this.RaisePropertyChanged("I_VALOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string I_CUENTA {
            get {
                return this.i_CUENTAField;
            }
            set {
                this.i_CUENTAField = value;
                this.RaisePropertyChanged("I_CUENTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string I_SISTEMA {
            get {
                return this.i_SISTEMAField;
            }
            set {
                this.i_SISTEMAField = value;
                this.RaisePropertyChanged("I_SISTEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string I_PRODUCTO {
            get {
                return this.i_PRODUCTOField;
            }
            set {
                this.i_PRODUCTOField = value;
                this.RaisePropertyChanged("I_PRODUCTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string I_TIPOTRN {
            get {
                return this.i_TIPOTRNField;
            }
            set {
                this.i_TIPOTRNField = value;
                this.RaisePropertyChanged("I_TIPOTRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public iLISTAREGISTROS I_LISTAREGISTROS {
            get {
                return this.i_LISTAREGISTROSField;
            }
            set {
                this.i_LISTAREGISTROSField = value;
                this.RaisePropertyChanged("I_LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/")]
    public partial class iLISTAREGISTROS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long i_RTNCONField;
        
        private iLISTAREGISTROSLIST[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long I_RTNCON {
            get {
                return this.i_RTNCONField;
            }
            set {
                this.i_RTNCONField = value;
                this.RaisePropertyChanged("I_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public iLISTAREGISTROSLIST[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/")]
    public partial class iLISTAREGISTROSLIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_MONEDAField;
        
        private string i_TIPMONField;
        
        private string i_CODDENField;
        
        private string i_CANDENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_MONEDA {
            get {
                return this.i_MONEDAField;
            }
            set {
                this.i_MONEDAField = value;
                this.RaisePropertyChanged("I_MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_TIPMON {
            get {
                return this.i_TIPMONField;
            }
            set {
                this.i_TIPMONField = value;
                this.RaisePropertyChanged("I_TIPMON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_CODDEN {
            get {
                return this.i_CODDENField;
            }
            set {
                this.i_CODDENField = value;
                this.RaisePropertyChanged("I_CODDEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANDEN {
            get {
                return this.i_CANDENField;
            }
            set {
                this.i_CANDENField = value;
                this.RaisePropertyChanged("I_CANDEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/")]
    public partial class mtrprotrnResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_CODIGOAUTORIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_CODIGOAUTORI {
            get {
                return this.o_CODIGOAUTORIField;
            }
            set {
                this.o_CODIGOAUTORIField = value;
                this.RaisePropertyChanged("O_CODIGOAUTORI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrprotrn", WrapperNamespace="http://procesartransaccion.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrprotrnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ReportTransaction.mtrprotrnInput arg0;
        
        public mtrprotrnRequest() {
        }
        
        public mtrprotrnRequest(WPFMultired.MR_ReportTransaction.mtrprotrnInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrprotrnResponse", WrapperNamespace="http://procesartransaccion.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrprotrnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://procesartransaccion.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_ReportTransaction.mtrprotrnResult @return;
        
        public mtrprotrnResponse() {
        }
        
        public mtrprotrnResponse(WPFMultired.MR_ReportTransaction.mtrprotrnResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcesarTransaccionServicesChannel : WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcesarTransaccionServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices>, WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices {
        
        public ProcesarTransaccionServicesClient() {
        }
        
        public ProcesarTransaccionServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcesarTransaccionServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesarTransaccionServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesarTransaccionServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_ReportTransaction.mtrprotrnResponse WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices.mtrprotrn(WPFMultired.MR_ReportTransaction.mtrprotrnRequest request) {
            return base.Channel.mtrprotrn(request);
        }
        
        public WPFMultired.MR_ReportTransaction.mtrprotrnResult mtrprotrn(WPFMultired.MR_ReportTransaction.mtrprotrnInput arg0) {
            WPFMultired.MR_ReportTransaction.mtrprotrnRequest inValue = new WPFMultired.MR_ReportTransaction.mtrprotrnRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_ReportTransaction.mtrprotrnResponse retVal = ((WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices)(this)).mtrprotrn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_ReportTransaction.mtrprotrnResponse> WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices.mtrprotrnAsync(WPFMultired.MR_ReportTransaction.mtrprotrnRequest request) {
            return base.Channel.mtrprotrnAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_ReportTransaction.mtrprotrnResponse> mtrprotrnAsync(WPFMultired.MR_ReportTransaction.mtrprotrnInput arg0) {
            WPFMultired.MR_ReportTransaction.mtrprotrnRequest inValue = new WPFMultired.MR_ReportTransaction.mtrprotrnRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_ReportTransaction.ProcesarTransaccionServices)(this)).mtrprotrnAsync(inValue);
        }
    }
}
