//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_TypeDocument {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/", ConfigurationName="MR_TypeDocument.ConsultarTiposDeDocumentoServices")]
    public interface ConsultarTiposDeDocumentoServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://consultartiposdedocumento.wsbeans.iseries/ConsultarTiposDeDocumentoService" +
            "s/mtrtipdoccRequest", ReplyAction="http://consultartiposdedocumento.wsbeans.iseries/ConsultarTiposDeDocumentoService" +
            "s/mtrtipdoccResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_TypeDocument.mtrtipdoccResponse mtrtipdocc(WPFMultired.MR_TypeDocument.mtrtipdoccRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://consultartiposdedocumento.wsbeans.iseries/ConsultarTiposDeDocumentoService" +
            "s/mtrtipdoccRequest", ReplyAction="http://consultartiposdedocumento.wsbeans.iseries/ConsultarTiposDeDocumentoService" +
            "s/mtrtipdoccResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrtipdoccResponse> mtrtipdoccAsync(WPFMultired.MR_TypeDocument.mtrtipdoccRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/")]
    public partial class mtrtipdoccInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/")]
    public partial class listaregistroslist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODTIPField;
        
        private string o_DESTIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODTIP {
            get {
                return this.o_CODTIPField;
            }
            set {
                this.o_CODTIPField = value;
                this.RaisePropertyChanged("O_CODTIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_DESTIP {
            get {
                return this.o_DESTIPField;
            }
            set {
                this.o_DESTIPField = value;
                this.RaisePropertyChanged("O_DESTIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/")]
    public partial class listaregistros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int o_RTNCONField;
        
        private listaregistroslist[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int O_RTNCON {
            get {
                return this.o_RTNCONField;
            }
            set {
                this.o_RTNCONField = value;
                this.RaisePropertyChanged("O_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public listaregistroslist[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/")]
    public partial class mtrtipdoccResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private listaregistros lISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public listaregistros LISTAREGISTROS {
            get {
                return this.lISTAREGISTROSField;
            }
            set {
                this.lISTAREGISTROSField = value;
                this.RaisePropertyChanged("LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrtipdocc", WrapperNamespace="http://consultartiposdedocumento.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrtipdoccRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeDocument.mtrtipdoccInput arg0;
        
        public mtrtipdoccRequest() {
        }
        
        public mtrtipdoccRequest(WPFMultired.MR_TypeDocument.mtrtipdoccInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrtipdoccResponse", WrapperNamespace="http://consultartiposdedocumento.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrtipdoccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultartiposdedocumento.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeDocument.mtrtipdoccResult @return;
        
        public mtrtipdoccResponse() {
        }
        
        public mtrtipdoccResponse(WPFMultired.MR_TypeDocument.mtrtipdoccResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarTiposDeDocumentoServicesChannel : WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarTiposDeDocumentoServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices>, WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices {
        
        public ConsultarTiposDeDocumentoServicesClient() {
        }
        
        public ConsultarTiposDeDocumentoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarTiposDeDocumentoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarTiposDeDocumentoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarTiposDeDocumentoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_TypeDocument.mtrtipdoccResponse WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices.mtrtipdocc(WPFMultired.MR_TypeDocument.mtrtipdoccRequest request) {
            return base.Channel.mtrtipdocc(request);
        }
        
        public WPFMultired.MR_TypeDocument.mtrtipdoccResult mtrtipdocc(WPFMultired.MR_TypeDocument.mtrtipdoccInput arg0) {
            WPFMultired.MR_TypeDocument.mtrtipdoccRequest inValue = new WPFMultired.MR_TypeDocument.mtrtipdoccRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_TypeDocument.mtrtipdoccResponse retVal = ((WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices)(this)).mtrtipdocc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrtipdoccResponse> WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices.mtrtipdoccAsync(WPFMultired.MR_TypeDocument.mtrtipdoccRequest request) {
            return base.Channel.mtrtipdoccAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrtipdoccResponse> mtrtipdoccAsync(WPFMultired.MR_TypeDocument.mtrtipdoccInput arg0) {
            WPFMultired.MR_TypeDocument.mtrtipdoccRequest inValue = new WPFMultired.MR_TypeDocument.mtrtipdoccRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_TypeDocument.ConsultarTiposDeDocumentoServices)(this)).mtrtipdoccAsync(inValue);
        }
    }
}
