//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_TypeDocument {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/", ConfigurationName="MR_TypeDocument.TiposDocumentosServices")]
    public interface TiposDocumentosServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tiposdocumentos.wsbeans.iseries/TiposDocumentosServices/mtrdoctrncRequest", ReplyAction="http://tiposdocumentos.wsbeans.iseries/TiposDocumentosServices/mtrdoctrncResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_TypeDocument.mtrdoctrncResponse mtrdoctrnc(WPFMultired.MR_TypeDocument.mtrdoctrncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tiposdocumentos.wsbeans.iseries/TiposDocumentosServices/mtrdoctrncRequest", ReplyAction="http://tiposdocumentos.wsbeans.iseries/TiposDocumentosServices/mtrdoctrncResponse" +
            "")]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrdoctrncResponse> mtrdoctrncAsync(WPFMultired.MR_TypeDocument.mtrdoctrncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/")]
    public partial class mtrdoctrncInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TIPOTRANSACCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TIPOTRANSACCION {
            get {
                return this.i_TIPOTRANSACCIONField;
            }
            set {
                this.i_TIPOTRANSACCIONField = value;
                this.RaisePropertyChanged("I_TIPOTRANSACCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/")]
    public partial class listaregistroslist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_TIPDOCField;
        
        private string o_DSCDOCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_TIPDOC {
            get {
                return this.o_TIPDOCField;
            }
            set {
                this.o_TIPDOCField = value;
                this.RaisePropertyChanged("O_TIPDOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_DSCDOC {
            get {
                return this.o_DSCDOCField;
            }
            set {
                this.o_DSCDOCField = value;
                this.RaisePropertyChanged("O_DSCDOC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/")]
    public partial class listaregistros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long o_RTNCONField;
        
        private listaregistroslist[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long O_RTNCON {
            get {
                return this.o_RTNCONField;
            }
            set {
                this.o_RTNCONField = value;
                this.RaisePropertyChanged("O_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public listaregistroslist[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/")]
    public partial class mtrdoctrncResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private listaregistros lISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public listaregistros LISTAREGISTROS {
            get {
                return this.lISTAREGISTROSField;
            }
            set {
                this.lISTAREGISTROSField = value;
                this.RaisePropertyChanged("LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrdoctrnc", WrapperNamespace="http://tiposdocumentos.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrdoctrncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeDocument.mtrdoctrncInput arg0;
        
        public mtrdoctrncRequest() {
        }
        
        public mtrdoctrncRequest(WPFMultired.MR_TypeDocument.mtrdoctrncInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrdoctrncResponse", WrapperNamespace="http://tiposdocumentos.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrdoctrncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tiposdocumentos.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeDocument.mtrdoctrncResult @return;
        
        public mtrdoctrncResponse() {
        }
        
        public mtrdoctrncResponse(WPFMultired.MR_TypeDocument.mtrdoctrncResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiposDocumentosServicesChannel : WPFMultired.MR_TypeDocument.TiposDocumentosServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiposDocumentosServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_TypeDocument.TiposDocumentosServices>, WPFMultired.MR_TypeDocument.TiposDocumentosServices {
        
        public TiposDocumentosServicesClient() {
        }
        
        public TiposDocumentosServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiposDocumentosServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposDocumentosServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposDocumentosServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_TypeDocument.mtrdoctrncResponse WPFMultired.MR_TypeDocument.TiposDocumentosServices.mtrdoctrnc(WPFMultired.MR_TypeDocument.mtrdoctrncRequest request) {
            return base.Channel.mtrdoctrnc(request);
        }
        
        public WPFMultired.MR_TypeDocument.mtrdoctrncResult mtrdoctrnc(WPFMultired.MR_TypeDocument.mtrdoctrncInput arg0) {
            WPFMultired.MR_TypeDocument.mtrdoctrncRequest inValue = new WPFMultired.MR_TypeDocument.mtrdoctrncRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_TypeDocument.mtrdoctrncResponse retVal = ((WPFMultired.MR_TypeDocument.TiposDocumentosServices)(this)).mtrdoctrnc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrdoctrncResponse> WPFMultired.MR_TypeDocument.TiposDocumentosServices.mtrdoctrncAsync(WPFMultired.MR_TypeDocument.mtrdoctrncRequest request) {
            return base.Channel.mtrdoctrncAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_TypeDocument.mtrdoctrncResponse> mtrdoctrncAsync(WPFMultired.MR_TypeDocument.mtrdoctrncInput arg0) {
            WPFMultired.MR_TypeDocument.mtrdoctrncRequest inValue = new WPFMultired.MR_TypeDocument.mtrdoctrncRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_TypeDocument.TiposDocumentosServices)(this)).mtrdoctrncAsync(inValue);
        }
    }
}
