//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_TypeTransaction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/", ConfigurationName="MR_TypeTransaction.ConsultarTiposDeTransaccionServices")]
    public interface ConsultarTiposDeTransaccionServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://consultartiposdetransaccion.wsbeans.iseries/ConsultarTiposDeTransaccionSer" +
            "vices/mtrtiptrnRequest", ReplyAction="http://consultartiposdetransaccion.wsbeans.iseries/ConsultarTiposDeTransaccionSer" +
            "vices/mtrtiptrnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_TypeTransaction.mtrtiptrnResponse mtrtiptrn(WPFMultired.MR_TypeTransaction.mtrtiptrnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://consultartiposdetransaccion.wsbeans.iseries/ConsultarTiposDeTransaccionSer" +
            "vices/mtrtiptrnRequest", ReplyAction="http://consultartiposdetransaccion.wsbeans.iseries/ConsultarTiposDeTransaccionSer" +
            "vices/mtrtiptrnResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeTransaction.mtrtiptrnResponse> mtrtiptrnAsync(WPFMultired.MR_TypeTransaction.mtrtiptrnRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/")]
    public partial class mtrtiptrnInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/")]
    public partial class oLISTAREGISTROSLIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_TIPTRNField;
        
        private string o_DSCTRNField;
        
        private string o_ENTRECField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_TIPTRN {
            get {
                return this.o_TIPTRNField;
            }
            set {
                this.o_TIPTRNField = value;
                this.RaisePropertyChanged("O_TIPTRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_DSCTRN {
            get {
                return this.o_DSCTRNField;
            }
            set {
                this.o_DSCTRNField = value;
                this.RaisePropertyChanged("O_DSCTRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_ENTREC {
            get {
                return this.o_ENTRECField;
            }
            set {
                this.o_ENTRECField = value;
                this.RaisePropertyChanged("O_ENTREC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/")]
    public partial class oLISTAREGISTROS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long o_RTNCONField;
        
        private oLISTAREGISTROSLIST[] lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long O_RTNCON {
            get {
                return this.o_RTNCONField;
            }
            set {
                this.o_RTNCONField = value;
                this.RaisePropertyChanged("O_RTNCON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public oLISTAREGISTROSLIST[] LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/")]
    public partial class mtrtiptrnResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private oLISTAREGISTROS o_LISTAREGISTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public oLISTAREGISTROS O_LISTAREGISTROS {
            get {
                return this.o_LISTAREGISTROSField;
            }
            set {
                this.o_LISTAREGISTROSField = value;
                this.RaisePropertyChanged("O_LISTAREGISTROS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrtiptrn", WrapperNamespace="http://consultartiposdetransaccion.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrtiptrnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeTransaction.mtrtiptrnInput arg0;
        
        public mtrtiptrnRequest() {
        }
        
        public mtrtiptrnRequest(WPFMultired.MR_TypeTransaction.mtrtiptrnInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrtiptrnResponse", WrapperNamespace="http://consultartiposdetransaccion.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrtiptrnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://consultartiposdetransaccion.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_TypeTransaction.mtrtiptrnResult @return;
        
        public mtrtiptrnResponse() {
        }
        
        public mtrtiptrnResponse(WPFMultired.MR_TypeTransaction.mtrtiptrnResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarTiposDeTransaccionServicesChannel : WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarTiposDeTransaccionServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices>, WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices {
        
        public ConsultarTiposDeTransaccionServicesClient() {
        }
        
        public ConsultarTiposDeTransaccionServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarTiposDeTransaccionServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarTiposDeTransaccionServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarTiposDeTransaccionServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_TypeTransaction.mtrtiptrnResponse WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices.mtrtiptrn(WPFMultired.MR_TypeTransaction.mtrtiptrnRequest request) {
            return base.Channel.mtrtiptrn(request);
        }
        
        public WPFMultired.MR_TypeTransaction.mtrtiptrnResult mtrtiptrn(WPFMultired.MR_TypeTransaction.mtrtiptrnInput arg0) {
            WPFMultired.MR_TypeTransaction.mtrtiptrnRequest inValue = new WPFMultired.MR_TypeTransaction.mtrtiptrnRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_TypeTransaction.mtrtiptrnResponse retVal = ((WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices)(this)).mtrtiptrn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_TypeTransaction.mtrtiptrnResponse> WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices.mtrtiptrnAsync(WPFMultired.MR_TypeTransaction.mtrtiptrnRequest request) {
            return base.Channel.mtrtiptrnAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_TypeTransaction.mtrtiptrnResponse> mtrtiptrnAsync(WPFMultired.MR_TypeTransaction.mtrtiptrnInput arg0) {
            WPFMultired.MR_TypeTransaction.mtrtiptrnRequest inValue = new WPFMultired.MR_TypeTransaction.mtrtiptrnRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_TypeTransaction.ConsultarTiposDeTransaccionServices)(this)).mtrtiptrnAsync(inValue);
        }
    }
}
