//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_RetirosRed {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://retirosred.wsbeans.iseries/", ConfigurationName="MR_RetirosRed.RetirosRedServices")]
    public interface RetirosRedServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://retirosred.wsbeans.iseries/RetirosRedServices/mtrretirocRequest", ReplyAction="http://retirosred.wsbeans.iseries/RetirosRedServices/mtrretirocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_RetirosRed.mtrretirocResponse mtrretiroc(WPFMultired.MR_RetirosRed.mtrretirocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://retirosred.wsbeans.iseries/RetirosRedServices/mtrretirocRequest", ReplyAction="http://retirosred.wsbeans.iseries/RetirosRedServices/mtrretirocResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_RetirosRed.mtrretirocResponse> mtrretirocAsync(WPFMultired.MR_RetirosRed.mtrretirocRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retirosred.wsbeans.iseries/")]
    public partial class mtrretirocInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_KEYASMField;
        
        private string i_KEYREDField;
        
        private string i_VALORRECAUDADOField;
        
        private string i_VALORDEVUELTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_KEYASM {
            get {
                return this.i_KEYASMField;
            }
            set {
                this.i_KEYASMField = value;
                this.RaisePropertyChanged("I_KEYASM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_KEYRED {
            get {
                return this.i_KEYREDField;
            }
            set {
                this.i_KEYREDField = value;
                this.RaisePropertyChanged("I_KEYRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_VALORRECAUDADO {
            get {
                return this.i_VALORRECAUDADOField;
            }
            set {
                this.i_VALORRECAUDADOField = value;
                this.RaisePropertyChanged("I_VALORRECAUDADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_VALORDEVUELTO {
            get {
                return this.i_VALORDEVUELTOField;
            }
            set {
                this.i_VALORDEVUELTOField = value;
                this.RaisePropertyChanged("I_VALORDEVUELTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retirosred.wsbeans.iseries/")]
    public partial class mtrretirocResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_NUMERODOCUMENTOField;
        
        private string o_NOMBREField;
        
        private string o_REFERENCIAField;
        
        private string o_FECHATRANSACCIONField;
        
        private string o_APROBACIONField;
        
        private string o_VALORTOTALField;
        
        private string o_VALORRECAUDADOField;
        
        private string o_VALOREXCESOField;
        
        private string o_VALORCOMISIONField;
        
        private string o_LLAVEMULTIREDField;
        
        private string o_NOMBREENTIDADField;
        
        private string o_DATOSADICIONALESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_NUMERODOCUMENTO {
            get {
                return this.o_NUMERODOCUMENTOField;
            }
            set {
                this.o_NUMERODOCUMENTOField = value;
                this.RaisePropertyChanged("O_NUMERODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_NOMBRE {
            get {
                return this.o_NOMBREField;
            }
            set {
                this.o_NOMBREField = value;
                this.RaisePropertyChanged("O_NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_REFERENCIA {
            get {
                return this.o_REFERENCIAField;
            }
            set {
                this.o_REFERENCIAField = value;
                this.RaisePropertyChanged("O_REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_FECHATRANSACCION {
            get {
                return this.o_FECHATRANSACCIONField;
            }
            set {
                this.o_FECHATRANSACCIONField = value;
                this.RaisePropertyChanged("O_FECHATRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string O_APROBACION {
            get {
                return this.o_APROBACIONField;
            }
            set {
                this.o_APROBACIONField = value;
                this.RaisePropertyChanged("O_APROBACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string O_VALORTOTAL {
            get {
                return this.o_VALORTOTALField;
            }
            set {
                this.o_VALORTOTALField = value;
                this.RaisePropertyChanged("O_VALORTOTAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string O_VALORRECAUDADO {
            get {
                return this.o_VALORRECAUDADOField;
            }
            set {
                this.o_VALORRECAUDADOField = value;
                this.RaisePropertyChanged("O_VALORRECAUDADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string O_VALOREXCESO {
            get {
                return this.o_VALOREXCESOField;
            }
            set {
                this.o_VALOREXCESOField = value;
                this.RaisePropertyChanged("O_VALOREXCESO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string O_VALORCOMISION {
            get {
                return this.o_VALORCOMISIONField;
            }
            set {
                this.o_VALORCOMISIONField = value;
                this.RaisePropertyChanged("O_VALORCOMISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string O_LLAVEMULTIRED {
            get {
                return this.o_LLAVEMULTIREDField;
            }
            set {
                this.o_LLAVEMULTIREDField = value;
                this.RaisePropertyChanged("O_LLAVEMULTIRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string O_NOMBREENTIDAD {
            get {
                return this.o_NOMBREENTIDADField;
            }
            set {
                this.o_NOMBREENTIDADField = value;
                this.RaisePropertyChanged("O_NOMBREENTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string O_DATOSADICIONALES {
            get {
                return this.o_DATOSADICIONALESField;
            }
            set {
                this.o_DATOSADICIONALESField = value;
                this.RaisePropertyChanged("O_DATOSADICIONALES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrretiroc", WrapperNamespace="http://retirosred.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrretirocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retirosred.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_RetirosRed.mtrretirocInput arg0;
        
        public mtrretirocRequest() {
        }
        
        public mtrretirocRequest(WPFMultired.MR_RetirosRed.mtrretirocInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrretirocResponse", WrapperNamespace="http://retirosred.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrretirocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retirosred.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_RetirosRed.mtrretirocResult @return;
        
        public mtrretirocResponse() {
        }
        
        public mtrretirocResponse(WPFMultired.MR_RetirosRed.mtrretirocResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetirosRedServicesChannel : WPFMultired.MR_RetirosRed.RetirosRedServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetirosRedServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_RetirosRed.RetirosRedServices>, WPFMultired.MR_RetirosRed.RetirosRedServices {
        
        public RetirosRedServicesClient() {
        }
        
        public RetirosRedServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetirosRedServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetirosRedServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetirosRedServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_RetirosRed.mtrretirocResponse WPFMultired.MR_RetirosRed.RetirosRedServices.mtrretiroc(WPFMultired.MR_RetirosRed.mtrretirocRequest request) {
            return base.Channel.mtrretiroc(request);
        }
        
        public WPFMultired.MR_RetirosRed.mtrretirocResult mtrretiroc(WPFMultired.MR_RetirosRed.mtrretirocInput arg0) {
            WPFMultired.MR_RetirosRed.mtrretirocRequest inValue = new WPFMultired.MR_RetirosRed.mtrretirocRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_RetirosRed.mtrretirocResponse retVal = ((WPFMultired.MR_RetirosRed.RetirosRedServices)(this)).mtrretiroc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_RetirosRed.mtrretirocResponse> WPFMultired.MR_RetirosRed.RetirosRedServices.mtrretirocAsync(WPFMultired.MR_RetirosRed.mtrretirocRequest request) {
            return base.Channel.mtrretirocAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_RetirosRed.mtrretirocResponse> mtrretirocAsync(WPFMultired.MR_RetirosRed.mtrretirocInput arg0) {
            WPFMultired.MR_RetirosRed.mtrretirocRequest inValue = new WPFMultired.MR_RetirosRed.mtrretirocRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_RetirosRed.RetirosRedServices)(this)).mtrretirocAsync(inValue);
        }
    }
}
