//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_FingerprintValidator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validarhuella.wsbeans.iseries/", ConfigurationName="MR_FingerprintValidator.ValidarHuellaServices")]
    public interface ValidarHuellaServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://validarhuella.wsbeans.iseries/ValidarHuellaServices/mtrhuellacRequest", ReplyAction="http://validarhuella.wsbeans.iseries/ValidarHuellaServices/mtrhuellacResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_FingerprintValidator.mtrhuellacResponse mtrhuellac(WPFMultired.MR_FingerprintValidator.mtrhuellacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validarhuella.wsbeans.iseries/ValidarHuellaServices/mtrhuellacRequest", ReplyAction="http://validarhuella.wsbeans.iseries/ValidarHuellaServices/mtrhuellacResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_FingerprintValidator.mtrhuellacResponse> mtrhuellacAsync(WPFMultired.MR_FingerprintValidator.mtrhuellacRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validarhuella.wsbeans.iseries/")]
    public partial class mtrhuellacInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_TIPODOCUMENTOField;
        
        private string i_DOCUMENTOField;
        
        private string i_TIPOTRANSACCIONField;
        
        private string i_ACCIONField;
        
        private iHUELLA i_HUELLAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_TIPODOCUMENTO {
            get {
                return this.i_TIPODOCUMENTOField;
            }
            set {
                this.i_TIPODOCUMENTOField = value;
                this.RaisePropertyChanged("I_TIPODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_DOCUMENTO {
            get {
                return this.i_DOCUMENTOField;
            }
            set {
                this.i_DOCUMENTOField = value;
                this.RaisePropertyChanged("I_DOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string I_TIPOTRANSACCION {
            get {
                return this.i_TIPOTRANSACCIONField;
            }
            set {
                this.i_TIPOTRANSACCIONField = value;
                this.RaisePropertyChanged("I_TIPOTRANSACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string I_ACCION {
            get {
                return this.i_ACCIONField;
            }
            set {
                this.i_ACCIONField = value;
                this.RaisePropertyChanged("I_ACCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public iHUELLA I_HUELLA {
            get {
                return this.i_HUELLAField;
            }
            set {
                this.i_HUELLAField = value;
                this.RaisePropertyChanged("I_HUELLA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validarhuella.wsbeans.iseries/")]
    public partial class iHUELLA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int i_HUELENField;
        
        private string i_HUEDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int I_HUELEN {
            get {
                return this.i_HUELENField;
            }
            set {
                this.i_HUELENField = value;
                this.RaisePropertyChanged("I_HUELEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_HUEDAT {
            get {
                return this.i_HUEDATField;
            }
            set {
                this.i_HUEDATField = value;
                this.RaisePropertyChanged("I_HUEDAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validarhuella.wsbeans.iseries/")]
    public partial class mtrhuellacResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_ENROLLEDField;
        
        private string o_HANDField;
        
        private string o_FINGERField;
        
        private string o_ISVALIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_ENROLLED {
            get {
                return this.o_ENROLLEDField;
            }
            set {
                this.o_ENROLLEDField = value;
                this.RaisePropertyChanged("O_ENROLLED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string O_HAND {
            get {
                return this.o_HANDField;
            }
            set {
                this.o_HANDField = value;
                this.RaisePropertyChanged("O_HAND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string O_FINGER {
            get {
                return this.o_FINGERField;
            }
            set {
                this.o_FINGERField = value;
                this.RaisePropertyChanged("O_FINGER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string O_ISVALID {
            get {
                return this.o_ISVALIDField;
            }
            set {
                this.o_ISVALIDField = value;
                this.RaisePropertyChanged("O_ISVALID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrhuellac", WrapperNamespace="http://validarhuella.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrhuellacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validarhuella.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_FingerprintValidator.mtrhuellacInput arg0;
        
        public mtrhuellacRequest() {
        }
        
        public mtrhuellacRequest(WPFMultired.MR_FingerprintValidator.mtrhuellacInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrhuellacResponse", WrapperNamespace="http://validarhuella.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrhuellacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validarhuella.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_FingerprintValidator.mtrhuellacResult @return;
        
        public mtrhuellacResponse() {
        }
        
        public mtrhuellacResponse(WPFMultired.MR_FingerprintValidator.mtrhuellacResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidarHuellaServicesChannel : WPFMultired.MR_FingerprintValidator.ValidarHuellaServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarHuellaServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_FingerprintValidator.ValidarHuellaServices>, WPFMultired.MR_FingerprintValidator.ValidarHuellaServices {
        
        public ValidarHuellaServicesClient() {
        }
        
        public ValidarHuellaServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidarHuellaServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarHuellaServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarHuellaServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_FingerprintValidator.mtrhuellacResponse WPFMultired.MR_FingerprintValidator.ValidarHuellaServices.mtrhuellac(WPFMultired.MR_FingerprintValidator.mtrhuellacRequest request) {
            return base.Channel.mtrhuellac(request);
        }
        
        public WPFMultired.MR_FingerprintValidator.mtrhuellacResult mtrhuellac(WPFMultired.MR_FingerprintValidator.mtrhuellacInput arg0) {
            WPFMultired.MR_FingerprintValidator.mtrhuellacRequest inValue = new WPFMultired.MR_FingerprintValidator.mtrhuellacRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_FingerprintValidator.mtrhuellacResponse retVal = ((WPFMultired.MR_FingerprintValidator.ValidarHuellaServices)(this)).mtrhuellac(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_FingerprintValidator.mtrhuellacResponse> WPFMultired.MR_FingerprintValidator.ValidarHuellaServices.mtrhuellacAsync(WPFMultired.MR_FingerprintValidator.mtrhuellacRequest request) {
            return base.Channel.mtrhuellacAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_FingerprintValidator.mtrhuellacResponse> mtrhuellacAsync(WPFMultired.MR_FingerprintValidator.mtrhuellacInput arg0) {
            WPFMultired.MR_FingerprintValidator.mtrhuellacRequest inValue = new WPFMultired.MR_FingerprintValidator.mtrhuellacRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_FingerprintValidator.ValidarHuellaServices)(this)).mtrhuellacAsync(inValue);
        }
    }
}
