//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.MR_CodeTOTP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://totpmultired.wsbeans.iseries/", ConfigurationName="MR_CodeTOTP.TOTPMultiRedServices")]
    public interface TOTPMultiRedServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://totpmultired.wsbeans.iseries/TOTPMultiRedServices/mtrgetotpcRequest", ReplyAction="http://totpmultired.wsbeans.iseries/TOTPMultiRedServices/mtrgetotpcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFMultired.MR_CodeTOTP.mtrgetotpcResponse mtrgetotpc(WPFMultired.MR_CodeTOTP.mtrgetotpcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://totpmultired.wsbeans.iseries/TOTPMultiRedServices/mtrgetotpcRequest", ReplyAction="http://totpmultired.wsbeans.iseries/TOTPMultiRedServices/mtrgetotpcResponse")]
        System.Threading.Tasks.Task<WPFMultired.MR_CodeTOTP.mtrgetotpcResponse> mtrgetotpcAsync(WPFMultired.MR_CodeTOTP.mtrgetotpcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://totpmultired.wsbeans.iseries/")]
    public partial class mtrgetotpcInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_TERMINALField;
        
        private string i_DIRECCIONIPField;
        
        private string i_TIMESTAMPField;
        
        private string i_CANALField;
        
        private string i_LENGUAJEField;
        
        private string i_ENTIDADORIGENField;
        
        private string i_INSTITUCIONField;
        
        private string i_KEYREDField;
        
        private string i_NOMBREIMGField;
        
        private iIMAGEN i_IMAGENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_TERMINAL {
            get {
                return this.i_TERMINALField;
            }
            set {
                this.i_TERMINALField = value;
                this.RaisePropertyChanged("I_TERMINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_DIRECCIONIP {
            get {
                return this.i_DIRECCIONIPField;
            }
            set {
                this.i_DIRECCIONIPField = value;
                this.RaisePropertyChanged("I_DIRECCIONIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_TIMESTAMP {
            get {
                return this.i_TIMESTAMPField;
            }
            set {
                this.i_TIMESTAMPField = value;
                this.RaisePropertyChanged("I_TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_CANAL {
            get {
                return this.i_CANALField;
            }
            set {
                this.i_CANALField = value;
                this.RaisePropertyChanged("I_CANAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_LENGUAJE {
            get {
                return this.i_LENGUAJEField;
            }
            set {
                this.i_LENGUAJEField = value;
                this.RaisePropertyChanged("I_LENGUAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_ENTIDADORIGEN {
            get {
                return this.i_ENTIDADORIGENField;
            }
            set {
                this.i_ENTIDADORIGENField = value;
                this.RaisePropertyChanged("I_ENTIDADORIGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_INSTITUCION {
            get {
                return this.i_INSTITUCIONField;
            }
            set {
                this.i_INSTITUCIONField = value;
                this.RaisePropertyChanged("I_INSTITUCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string I_KEYRED {
            get {
                return this.i_KEYREDField;
            }
            set {
                this.i_KEYREDField = value;
                this.RaisePropertyChanged("I_KEYRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string I_NOMBREIMG {
            get {
                return this.i_NOMBREIMGField;
            }
            set {
                this.i_NOMBREIMGField = value;
                this.RaisePropertyChanged("I_NOMBREIMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public iIMAGEN I_IMAGEN {
            get {
                return this.i_IMAGENField;
            }
            set {
                this.i_IMAGENField = value;
                this.RaisePropertyChanged("I_IMAGEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://totpmultired.wsbeans.iseries/")]
    public partial class iIMAGEN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int i_IMGLENField;
        
        private string i_IMGDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int I_IMGLEN {
            get {
                return this.i_IMGLENField;
            }
            set {
                this.i_IMGLENField = value;
                this.RaisePropertyChanged("I_IMGLEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_IMGDAT {
            get {
                return this.i_IMGDATField;
            }
            set {
                this.i_IMGDATField = value;
                this.RaisePropertyChanged("I_IMGDAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://totpmultired.wsbeans.iseries/")]
    public partial class mtrgetotpcResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string o_CODIGOERRORField;
        
        private string o_MENSAJEERRORField;
        
        private string o_KEYOTPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string O_CODIGOERROR {
            get {
                return this.o_CODIGOERRORField;
            }
            set {
                this.o_CODIGOERRORField = value;
                this.RaisePropertyChanged("O_CODIGOERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string O_MENSAJEERROR {
            get {
                return this.o_MENSAJEERRORField;
            }
            set {
                this.o_MENSAJEERRORField = value;
                this.RaisePropertyChanged("O_MENSAJEERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string O_KEYOTP {
            get {
                return this.o_KEYOTPField;
            }
            set {
                this.o_KEYOTPField = value;
                this.RaisePropertyChanged("O_KEYOTP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrgetotpc", WrapperNamespace="http://totpmultired.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrgetotpcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://totpmultired.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_CodeTOTP.mtrgetotpcInput arg0;
        
        public mtrgetotpcRequest() {
        }
        
        public mtrgetotpcRequest(WPFMultired.MR_CodeTOTP.mtrgetotpcInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mtrgetotpcResponse", WrapperNamespace="http://totpmultired.wsbeans.iseries/", IsWrapped=true)]
    public partial class mtrgetotpcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://totpmultired.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFMultired.MR_CodeTOTP.mtrgetotpcResult @return;
        
        public mtrgetotpcResponse() {
        }
        
        public mtrgetotpcResponse(WPFMultired.MR_CodeTOTP.mtrgetotpcResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TOTPMultiRedServicesChannel : WPFMultired.MR_CodeTOTP.TOTPMultiRedServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TOTPMultiRedServicesClient : System.ServiceModel.ClientBase<WPFMultired.MR_CodeTOTP.TOTPMultiRedServices>, WPFMultired.MR_CodeTOTP.TOTPMultiRedServices {
        
        public TOTPMultiRedServicesClient() {
        }
        
        public TOTPMultiRedServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TOTPMultiRedServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TOTPMultiRedServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TOTPMultiRedServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFMultired.MR_CodeTOTP.mtrgetotpcResponse WPFMultired.MR_CodeTOTP.TOTPMultiRedServices.mtrgetotpc(WPFMultired.MR_CodeTOTP.mtrgetotpcRequest request) {
            return base.Channel.mtrgetotpc(request);
        }
        
        public WPFMultired.MR_CodeTOTP.mtrgetotpcResult mtrgetotpc(WPFMultired.MR_CodeTOTP.mtrgetotpcInput arg0) {
            WPFMultired.MR_CodeTOTP.mtrgetotpcRequest inValue = new WPFMultired.MR_CodeTOTP.mtrgetotpcRequest();
            inValue.arg0 = arg0;
            WPFMultired.MR_CodeTOTP.mtrgetotpcResponse retVal = ((WPFMultired.MR_CodeTOTP.TOTPMultiRedServices)(this)).mtrgetotpc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFMultired.MR_CodeTOTP.mtrgetotpcResponse> WPFMultired.MR_CodeTOTP.TOTPMultiRedServices.mtrgetotpcAsync(WPFMultired.MR_CodeTOTP.mtrgetotpcRequest request) {
            return base.Channel.mtrgetotpcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFMultired.MR_CodeTOTP.mtrgetotpcResponse> mtrgetotpcAsync(WPFMultired.MR_CodeTOTP.mtrgetotpcInput arg0) {
            WPFMultired.MR_CodeTOTP.mtrgetotpcRequest inValue = new WPFMultired.MR_CodeTOTP.mtrgetotpcRequest();
            inValue.arg0 = arg0;
            return ((WPFMultired.MR_CodeTOTP.TOTPMultiRedServices)(this)).mtrgetotpcAsync(inValue);
        }
    }
}
