//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMultired.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMultired.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea cancelar la transacción?.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estableciendo comunicación....
        /// </summary>
        internal static string ComunicationServer {
            get {
                return ResourceManager.GetString("ComunicationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se pudo establecer comunicación con el servidor!.
        /// </summary>
        internal static string ComunicationServerFail {
            get {
                return ResourceManager.GetString("ComunicationServerFail", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a ¿Desea  depositar la cantidad ingresada?.
=======
        ///   Looks up a localized string similar to ¿Desea consignar el monto ingresado?.
>>>>>>> e86d16f8b58940e2ae8e8882f5b7f7729da1097c
        /// </summary>
        internal static string ConsignAmount {
            get {
                return ResourceManager.GetString("ConsignAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos consultando las coincidencias. Regálenos unos segundos.
        /// </summary>
        internal static string ConsultingConinsidences {
            get {
                return ResourceManager.GetString("ConsultingConinsidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar {0}..
        /// </summary>
        internal static string EnterField {
            get {
                return ResourceManager.GetString("EnterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el NIT de la empresa.
        /// </summary>
        internal static string EnterId {
            get {
                return ResourceManager.GetString("EnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese los billetes y monedas que se indican a continuación en los dispositivos dispensador de billetes y dispensador de monedas.
        /// </summary>
        internal static string EnterMonyDispenser {
            get {
                return ResourceManager.GetString("EnterMonyDispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre de la empresa.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error! Por favor intentelo más tarde.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione los certificados que desea comprar.
        /// </summary>
        internal static string ErrorCertificate {
            get {
                return ResourceManager.GetString("ErrorCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error imprimiendo los certificados. se cancelara la transacción y devolverá el dinero ingresado.
        /// </summary>
        internal static string ErrorCertificatesPrint {
            get {
                return ResourceManager.GetString("ErrorCertificatesPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor usuario, no se encontraron coincidencias, vuelva a intentarlo.
        /// </summary>
        internal static string ErrorCoincidences {
            get {
                return ResourceManager.GetString("ErrorCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o contraseña incorrectos.
        /// </summary>
        internal static string ErrorDates {
            get {
                return ResourceManager.GetString("ErrorDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el momento no hay certificados para generar, vuelva pronto..
        /// </summary>
        internal static string ErrorFoundFiles {
            get {
                return ResourceManager.GetString("ErrorFoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un nit válido..
        /// </summary>
        internal static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un nombre válido..
        /// </summary>
        internal static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo no puede imprimir el comprobante en este momento, desea continuar.
        /// </summary>
        internal static string ErrorNoPaper {
            get {
                return ResourceManager.GetString("ErrorNoPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede continuar con la transacción. Se consignara el valor ingresado.
        /// </summary>
        internal static string ErrorPayment {
            get {
                return ResourceManager.GetString("ErrorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar la impresión de todos los certificatos. Por favor diríjase a las taquillas..
        /// </summary>
        internal static string ErrorPrintCertificate {
            get {
                return ResourceManager.GetString("ErrorPrintCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En este momento no se pueden imprimir certificados..
        /// </summary>
        internal static string ErrorPrinter {
            get {
                return ResourceManager.GetString("ErrorPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con el servicio de Login.
        /// </summary>
        internal static string ErrorServiceLogin {
            get {
                return ResourceManager.GetString("ErrorServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error, No se pudo completar la transacción.
        /// </summary>
        internal static string ErrorTransaction {
            get {
                return ResourceManager.GetString("ErrorTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo QR ingresado es inválido.
        /// </summary>
        internal static string ErrorValidaQr {
            get {
                return ResourceManager.GetString("ErrorValidaQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor usuario estamos Finalizando la transacción. Espere un momento..
        /// </summary>
        internal static string FinishTransaction {
            get {
                return ResourceManager.GetString("FinishTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se entrego completamente el dinero.
        /// </summary>
        internal static string IncompleteMony {
            get {
                return ResourceManager.GetString("IncompleteMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha ingresado información incorrecta, por favor validar la información y volver a intentarlo.
        /// </summary>
        internal static string InfoIncorrect {
            get {
                return ResourceManager.GetString("InfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El error se presentó al inicio del cajero.
        /// </summary>
        internal static string InformationError {
            get {
                return ResourceManager.GetString("InformationError", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Transacción en proceso por favor espere..
=======
        ///   Looks up a localized string similar to Se esta validando y almacenando la información, espere un momento por favor.
>>>>>>> e86d16f8b58940e2ae8e8882f5b7f7729da1097c
        /// </summary>
        internal static string LoadInformation {
            get {
                return ResourceManager.GetString("LoadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos contando su dinero, espere unos segundos.
        /// </summary>
        internal static string MessageReturnMony {
            get {
                return ResourceManager.GetString("MessageReturnMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo continuar entregando el dineroç.
        /// </summary>
        internal static string NoContinue {
            get {
                return ResourceManager.GetString("NoContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede continuar con la transacción. Intentelo más tarde.
        /// </summary>
        internal static string NoContinueTransaction {
            get {
                return ResourceManager.GetString("NoContinueTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro iniciar el paypad.
        /// </summary>
        internal static string NoGoInitial {
            get {
                return ResourceManager.GetString("NoGoInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin información para mostrar.
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos para mostrar en estos momentos..
        /// </summary>
        internal static string NoInfoShow {
            get {
                return ResourceManager.GetString("NoInfoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro insertar el pagador con id.
        /// </summary>
        internal static string NoInsertPayment {
            get {
                return ResourceManager.GetString("NoInsertPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro insertar la transacción.
        /// </summary>
        internal static string NoInsertTransaction {
            get {
                return ResourceManager.GetString("NoInsertTransaction", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a No se puede continuar con la transacción. por favor intentarlo mas tarde.
=======
        ///   Looks up a localized string similar to .
>>>>>>> e86d16f8b58940e2ae8e8882f5b7f7729da1097c
        /// </summary>
        internal static string NoProccessInformation {
            get {
                return ResourceManager.GetString("NoProccessInformation", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a El ASM está temporalmente fuera de servicio, por favor intente más tarde.
=======
        ///   Looks up a localized string similar to El cajero está fuera de servicio en este momento, por favor intente más tarde.
>>>>>>> e86d16f8b58940e2ae8e8882f5b7f7729da1097c
        /// </summary>
        internal static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción finalizó con novedad.
        /// </summary>
        internal static string NoveltyTransation {
            get {
                return ResourceManager.GetString("NoveltyTransation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cajero está fuera de servicio en este momento, por favor intente más tarde.
        /// </summary>
        internal static string OutService {
            get {
                return ResourceManager.GetString("OutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo entra en modo administrativo.
        /// </summary>
        internal static string PaypadGoAdmin {
            get {
                return ResourceManager.GetString("PaypadGoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo inicia correctamente.
        /// </summary>
        internal static string PaypadStarSusses {
            get {
                return ResourceManager.GetString("PaypadStarSusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de etiqueta negra.
        /// </summary>
        internal static string PrinterErrorTiketBlak {
            get {
                return ResourceManager.GetString("PrinterErrorTiketBlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El papel se agotará.
        /// </summary>
        internal static string PrinterExhaustPapper {
            get {
                return ResourceManager.GetString("PrinterExhaustPapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay papel en la impresora.
        /// </summary>
        internal static string PrinterNoPapper {
            get {
                return ResourceManager.GetString("PrinterNoPapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrecalentamiento de cabezal de impresión.
        /// </summary>
        internal static string PrinterOverheatingHeader {
            get {
                return ResourceManager.GetString("PrinterOverheatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La impresora y la biblioteca de llamadas no coinciden.
        /// </summary>
        internal static string PrintErrorLibrary {
            get {
                return ResourceManager.GetString("PrintErrorLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado de impresión abierto.
        /// </summary>
        internal static string PrintHeaderOpen {
            get {
                return ResourceManager.GetString("PrintHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La impresora no está conectada o encendida.
        /// </summary>
        internal static string PrintNoConect {
            get {
                return ResourceManager.GetString("PrintNoConect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La impresora está normal.
        /// </summary>
        internal static string PrintNormal {
            get {
                return ResourceManager.GetString("PrintNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuchillo de corte no RESET.
        /// </summary>
        internal static string PrintReset {
            get {
                return ResourceManager.GetString("PrintReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire los billetes y monedas que se indican a continuación, en los dispositivos aceptador de billetes y aceptador de monedas.
        /// </summary>
        internal static string RemoveMonyAceptance {
            get {
                return ResourceManager.GetString("RemoveMonyAceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire los billetes y monedas que se indican a continuación de los dispositivos dispensador de billetes y dispensador de monedas.
        /// </summary>
        internal static string RemoveMonyDispenser {
            get {
                return ResourceManager.GetString("RemoveMonyDispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado.
        /// </summary>
        internal static string StandarError {
            get {
                return ResourceManager.GetString("StandarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando estado del PayPlus....
        /// </summary>
        internal static string StatePayPlus {
            get {
                return ResourceManager.GetString("StatePayPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡El dispositivo no cuenta con cargue suficiente!.
        /// </summary>
        internal static string StatePayPlusFail {
            get {
                return ResourceManager.GetString("StatePayPlusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción exitosa.
        /// </summary>
        internal static string SussesTransaction {
            get {
                return ResourceManager.GetString("SussesTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción cancelada.
        /// </summary>
        internal static string TransactionCancel {
            get {
                return ResourceManager.GetString("TransactionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción ha finalizado correctamente..
        /// </summary>
        internal static string TransactionFinish {
            get {
                return ResourceManager.GetString("TransactionFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción finalizada correctamente.
        /// </summary>
        internal static string TransactionFinishSucces {
            get {
                return ResourceManager.GetString("TransactionFinishSucces", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Tiene una actualizacion pendiente por favor no manipule ni apague el PayPlus mientras termina la instalacion..
        /// </summary>
        internal static string UpdateAplication {
            get {
                return ResourceManager.GetString("UpdateAplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando perifericos....
=======
        ///   Looks up a localized string similar to Validando periférico ....
>>>>>>> e86d16f8b58940e2ae8e8882f5b7f7729da1097c
        /// </summary>
        internal static string ValidatePeripherals {
            get {
                return ResourceManager.GetString("ValidatePeripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se lograrón iniciar los dispositivos!.
        /// </summary>
        internal static string ValidatePeripheralsFail {
            get {
                return ResourceManager.GetString("ValidatePeripheralsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere mientras se configura el dispositivo para iniciar.
        /// </summary>
        internal static string WaitConfigurate {
            get {
                return ResourceManager.GetString("WaitConfigurate", resourceCulture);
            }
        }
    }
}
